### ISSUE TITLE
Use WireMock with Testcontainers or Dagger to test C4p Services

### ISSUE THREAD

**Issue by salaboy** [salaboy/platforms-on-k8s#20]
@mcruzdev Look into this: https://testcontainers.com/guides/testing-rest-api-integrations-using-wiremock/#_using_testcontainers_wiremock_module 

Right now, the C4p Service is starting the Agenda Service and the Notification Service to run its tests (to avoid local mocks) but with WireMock and Docker integration we can start a mocked version of the services instead of the real ones (that require redis and Kafka to be started). It will be interesting to see if we can get this working to improve those tests, as right now bootstrapping agenda and notifications with all the infra dependencies is way too much.

**Comment by mcruzdev** [comment]
TY! @salaboy

**Comment by mcruzdev** [comment]
Closed by #28
