### ISSUE TITLE
Chapter-02: Docker disk resource limit & typo

### ISSUE THREAD

**Issue by zouyingjie** [salaboy/platforms-on-k8s#21]
1. I'm running the service with a MacBook Pro m2 and I get the following error if the Docker disk space setting is too small.

```
$ > kind load docker-image -n dev bitnami/kafka:3.4.1-debian-11-r0                                                                                         base
Image: "bitnami/kafka:3.4.1-debian-11-r0" with ID "sha256:30edbaed7de3..." not yet present on node "dev-control-plane", loading...
...
Command Output: Error response from daemon: write /var/lib/docker/.../layer.tar: no space left on device
```
After adjusting the disk settings, the issue can be resolved. Would it be helpful to include a note about this in the documentation?

<img width="1066" alt="image" src="https://github.com/salaboy/platforms-on-k8s/assets/15356062/69c9e025-958a-484f-ae4b-9ce8fb411573">

2. The command ``kubect get pods`` contains a typo. ``kubect`` should be changed to ``kubectl``.

If there are any similar typo errors in the future, may I submit a PR directly?

**Comment by salaboy** [comment]
@zouyingjie thanks for reporting this, yes.. if you find typo issues, please submit a PR.

Do you want to submit a PR with a note that will help other users to set the right resources too?

**Comment by zouyingjie** [comment]
@salaboy  Of course, https://github.com/salaboy/platforms-on-k8s/pull/29
