### ISSUE TITLE
[Translations] Chinese Translation `zh_CN`

### ISSUE THREAD

**Issue by salaboy** [salaboy/platforms-on-k8s#24]
- [x] Main Index -> https://github.com/salaboy/platforms-on-k8s/pull/23
- [x] Chapter 1 -> https://github.com/salaboy/platforms-on-k8s/pull/23
- [x] Chapter 2 -> https://github.com/salaboy/platforms-on-k8s/pull/25
- [x] Chapter 3 -> https://github.com/salaboy/platforms-on-k8s/pull/30
- [x] Chapter 4 -> https://github.com/salaboy/platforms-on-k8s/pull/34
- [x] Chapter 5 -> https://github.com/salaboy/platforms-on-k8s/pull/45
- [x] Chapter 6 -> https://github.com/salaboy/platforms-on-k8s/pull/45
- [x] Chapter 7 -> https://github.com/salaboy/platforms-on-k8s/pull/46
- [x] Chapter 8 -> https://github.com/salaboy/platforms-on-k8s/pull/48
- [x] Chapter 9 -> https://github.com/salaboy/platforms-on-k8s/pull/49

**Comment by salaboy** [comment]
@fleeto, can you please rename the Chinese files to use `zh_CN` in the file name? That is the standard ISO code for the language.. meaning using the caps and the underscore. We will follow that for the other languages too

**Comment by fleeto** [comment]
ok I will rename them later

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by salaboy** [comment]
@fleeto we are still deciding the format.. so don't worry

**Comment by salaboy** [comment]
@fleeto this is amazing work in almost no time! Thanks a lot for your contributions, I will add you to the about section of the application as you provided all these valuable contributions.
