### ISSUE TITLE
test typos in book

### ISSUE THREAD

**Issue by busyboy77** [salaboy/platforms-on-k8s#59]
the highlighted text is placed incorrectly.

![image](https://github.com/salaboy/platforms-on-k8s/assets/19593617/4b54e6c5-21f6-4d29-a5e5-caffde5efd8a)

**Comment by salaboy** [comment]
@busyboy77 thanks for reporting this, I am not entirely sure where are you reading this, but this repo is only concerned about the tutorials that you can find inside the repository and not the text of the book. Please report using the tools that the editorial or the book platform that you are using gives you to report issues with the content/formatting of the text.
