### ISSUE TITLE
[Translations] Japanese ja_JP

### ISSUE THREAD

**Issue by nwiizo** [salaboy/platforms-on-k8s#61]
- [x] Main Index
- [x] Chapter 1
- [x] Chapter 2 
- [x] Chapter 3
- [x] Chapter 4
- [x] Chapter 5
- [x] Chapter 6
- [x] Chapter 7
- [x] Chapter 8
- [x] Chapter 9
- [x] Add the japanese link in the other languages

**Comment by salaboy** [comment]
@nwiizo thanks a lot for creating the issue! Let's do this!

**Comment by salaboy** [comment]
@nwiizo if you mention the issue with (Resolves https://github.com/salaboy/platforms-on-k8s/issues/61) the on the PR it will be closed automatically this issue.. so just add the link

**Comment by salaboy** [comment]
@nwiizo if you can translate this -> https://github.com/salaboy/platforms-on-k8s/blob/main/README.md and add the japanese link in the other languages, that would be awesome

**Comment by nwiizo** [comment]
I apologize for creating such a large number of pull requests. If you could please review them, I would greatly appreciate it. Thank you for taking the time to check over my work.

Please let me know if you need anything else or have any other questions!

**Comment by salaboy** [comment]
@nwiizo I've merged all the chapters.. you are a hero.. can you please do the main index and add the Japanese links in all the other languages?

**Comment by nwiizo** [comment]
@salaboy 
Thank you for merging all the chapters. That's fantastic work. I'd be happy to create the main index and add the Japanese links to all the other language pages.

Would you like me to proceed this way? Or did you have a different approach in mind?
https://github.com/salaboy/platforms-on-k8s/pull/70/files

**Comment by salaboy** [comment]
That's perfect! I've just added one more link that was missing and this is all done! thank you so much @nwiizo any feedback that you might have about the tutorials please let me know.
